export const REGION_GUIDES = [
  {
    slug: "optic-lobe",
    name: "OPTIC LOBE",
    scientificName: "optic lobe (ol_intrinsic / visual projection)",
    field: "official superclass → region",
    column: "region" as const,
    value: "optic_lobe",
    playful: "The cinema. Light becomes wiring.",
  },
  {
    slug: "central-brain",
    name: "CENTRAL BRAIN",
    scientificName: "central brain (cb_*)",
    field: "official superclass → region",
    column: "region" as const,
    value: "central_brain",
    playful: "The dense interior above the neck.",
  },
  {
    slug: "ventral-nerve-cord",
    name: "VENTRAL NERVE CORD",
    scientificName: "ventral nerve cord (vnc_*)",
    field: "official superclass → region",
    column: "region" as const,
    value: "ventral_nerve_cord",
    playful: "The spinal cord of the fly. Legs live here.",
  },
  {
    slug: "mushroom-body",
    name: "MUSHROOM BODY",
    scientificName: "Kenyon cells",
    field: "official class",
    column: "region" as const,
    value: "mushroom_body",
    playful: "The archive. Associations live here.",
  },
  {
    slug: "central-complex",
    name: "CENTRAL COMPLEX",
    scientificName: "class = CX",
    field: "official class → region",
    column: "region" as const,
    value: "central_complex",
    playful: "The compass room.",
  },
  {
    slug: "descending",
    name: "DESCENDING NEURONS",
    scientificName: "descending_neuron",
    field: "official superclass → region",
    column: "region" as const,
    value: "descending",
    playful: "Brain to body. The command line.",
  },
  {
    slug: "ascending",
    name: "ASCENDING NEURONS",
    scientificName: "ascending_neuron",
    field: "official superclass → region",
    column: "region" as const,
    value: "ascending",
    playful: "Body to brain. The return path.",
  },
  {
    slug: "intrinsic",
    name: "INTRINSIC CELLS",
    scientificName: "flow = intrinsic",
    field: "flow derived from official superclass",
    column: "flow" as const,
    value: "intrinsic",
    playful: "They never leave their neighbourhood.",
  },
  {
    slug: "afferent",
    name: "AFFERENTS",
    scientificName: "flow = afferent",
    field: "flow derived from official superclass",
    column: "flow" as const,
    value: "afferent",
    playful: "Incoming traffic.",
  },
  {
    slug: "efferent",
    name: "EFFERENTS",
    scientificName: "flow = efferent",
    field: "flow derived from official superclass",
    column: "flow" as const,
    value: "efferent",
    playful: "Outgoing traffic.",
  },
  {
    slug: "male-specific",
    name: "MALE-SPECIFIC",
    scientificName: "dimorphism = male-specific",
    field: "dimorphism",
    column: "dimorphism" as const,
    value: "male-specific",
    playful: "The cells the female brain does not keep.",
  },
];
